---
title: Nieuwe uiterlijken toevoegen in Scratch
hero_image: images/banner.png
description: Uiterlijken aan je sprite toevoegen
original_url:
theme: rood
duration: 1
listed: false
ingredient: true
copyedit: true
curriculum:
interests:
technologies: "scratch"
site_areas:
steps:
  - 
    title: Uiterlijken toevoegen

