---
title: Adăugarea de costume noi în Scratch
hero_image: images/banner.png
description: Adaugă costume noi la personajele tale
original_url:
theme: red #possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 1 #possible values: 1, 2 or 3
listed: false
ingredient: true
copyedit: true
curriculum:
interests:
technologies: "scratch"
site_areas:
steps:
  - title: Adăugarea de costume

