---
title: Adding new costumes in Scratch
hero_image: images/banner.png
description: Add costumes to your sprite
original_url:
theme: red
duration: 1
listed: false
ingredient: true
copyedit: true
curriculum:
interests:
technologies: "scratch"
site_areas:
steps:
  - 
    title: Add costumes

