---
title: Ajout de nouveaux costumes dans Scratch
hero_image: images/banner.png
description: Ajoute des costumes à ton sprite
original_url:
theme: red #possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 1 #possible values: 1, 2 or 3
listed: false
ingredient: true
copyedit: true
curriculum:
interests:
technologies: "scratch"
site_areas:
steps:
  - title: Ajouter des costumes

