---
title: Scratch'te yeni kostümler ekleme
hero_image: images/banner.png
description: Kuklanıza kostüm ekleyin
original_url:
theme: red
duration: 1
listed: false
ingredient: true
copyedit: true
curriculum:
interests:
technologies: "scratch"
site_areas:
steps:
  - 
    title: Kostüm ekle

